### ISSUE TITLE
oppoR9 失败.

### ISSUE THREAD

**Issue by TestSmirk** [hkq325800/JumpPermissionManagement#3]

**Comment by xiesw** [comment]
Intent intent = new Intent();
intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
intent.putExtra("pkg_name", context.getPackageName());
intent.putExtra("app_name", context.getString(R.string.app_name));
intent.putExtra("class_name", "com.welab.notificationdemo.MainActivity");
ComponentName comp = new ComponentName("com.coloros.notificationmanager", "com.coloros" +
".notificationmanager.AppDetailPreferenceActivity");
intent.setComponent(comp);
return intent;


class_name 写个跳转页面的报名就行
R9 colosos3.0.0  android5.1测试可以
